###
POST http://localhost:8778/

<> 2026-03-10T102924.200.txt

###
POST http://localhost:8778/correlate
Content-Type: application/json

{
  "businessKey": "5bca91d0-c2c9-4a80-b4f1-9fd3119cd1b5",
  "messageName": "TestMessage"
}

<> 2026-03-10T103044.500.json