###
POST http://localhost:8778/?name=EXCLUSIVE_GATEWAY

<> 2026-03-10T102924.200.txt

###
POST http://localhost:8778/correlate
Content-Type: application/json

{
  "businessKey": "180693ec-55f2-4047-8cb3-9501f79a3222",
  "messageName": "TestMessage"
}

<> 2026-03-10T103044.500.json